node('nodejs_runner_16') {
    stage('backend_checkout') {
        dir ('neo-api') {
        checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], \
        userRemoteConfigs: [[credentialsId: 'admingithub', url: 'git@github.com:Gemini-Solutions/GemMobil.git', poll: 'false']]])
        }
    }
    stage('Nodejs_Build') {
        container('nodejs-16') {
            dir ('neo-api'){
                sh 'rm -rf package-lock.json'
                //sh 'npm cache clean --force'
                sh 'npm install'
                sh 'npm run build'
            }
        }
    }
}
node('image_builder_trivy') {
    try {
        stage('Build_image') {
            dir ('neo-api') {
                container('docker-image-builder-trivy') {
                    withCredentials([usernamePassword (credentialsId: 'docker_registry', passwordVariable: 'docker_pass', usernameVariable: 'docker_user')]) {
                        sh 'docker image build -f Dockerfile -t registry-np.geminisolutions.com/neo/neo-api:1.0-$BUILD_NUMBER -t registry-np.geminisolutions.com/neo/neo-api .'
                        sh 'trivy image -f json registry-np.geminisolutions.com/neo/neo-api:1.0-$BUILD_NUMBER > trivy-report.json'
                        archiveArtifacts artifacts: 'trivy-report.json', onlyIfSuccessful: true
                        sh '''docker login -u $docker_user -p $docker_pass https://registry-np.geminisolutions.com'''
                        sh 'docker push registry-np.geminisolutions.com/neo/neo-api:1.0-$BUILD_NUMBER'
                        sh 'docker push registry-np.geminisolutions.com/neo/neo-api'
                        sh 'rm -rf build/'
                    }
                }
            }
        }
    stage('Deployment_stage') {
        dir ('neo-api') {
            container('docker-image-builder-trivy') {
                kubeconfig(credentialsId: 'KubeConfigCred') {
                    sh '/usr/local/bin/kubectl apply -f Deployment-beta.yaml -n dev'
                    sh '/usr/local/bin/kubectl rollout restart Deployment neodev -n  dev'
                }
            }
        }
    }
    } finally {
//         sh 'echo current_image="registry-np.geminisolutions.com/neo/neo-api:1.0-$BUILD_NUMBER" > build.properties'
//         archiveArtifacts artifacts: 'build.properties', onlyIfSuccessful: true
    }
}
